[package]
name = "TeamComments"
author = "David Minnerly"
license = "MIT"
content_root = "src"
version = "1.0.0"

[dependencies]
Promise = "https://github.com/evaera/roblox-lua-promise@3.1.0"
Roact = "https://github.com/Roblox/roact@1.4.0"
t = "https://github.com/Roblox/t@1.2.5"
