[package]
name = "vocksel/team-comments"
version = "1.0.0"
authors = [ "David Minnerly <me@vocksel.com>" ]
license = "MIT"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"
exclude = [ "*" ]

[dependencies]
Promise = "evaera/promise@3.2.0"
Roact = "roblox/roact@1.4.2"
Hooks = "kampfkarren/roact-hooks@0.3.0"
Flipper = "reselim/flipper@2.0.0"
t = "osyrisrblx/t@3.0.0"
Llama = "freddylist/llama@1.1.1"
