[package]
name = "vocksel/team-comments"
version = "1.0.0"
authors = [ "David Minnerly <me@vocksel.com>" ]
license = "MIT"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"
exclude = [ "*" ]

[dependencies]
Promise = "evaera/promise@3.2.0"
React = "jsdotlua/react@17.0.2"
ReactRoblox = "jsdotlua/react-roblox@17.0.2"
Flipper = "reselim/flipper@2.0.0"
Llama = "freddylist/llama@1.1.1"

[dev-dependencies]
TestEZ = "roblox/testez@0.4.1"
